###Server Port###
server:
  port: 8081
###Application name###
spring:
  application:
    name: CARDS-SERVICE
  ###Database connection###
  datasource:
    url: jdbc:mysql://localhost:3306/cards?autoReconnect=true&allowPublicKeyRetrieval=true
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  ##Show jpa sql###
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
###Logging in external file###
logging:
  file:
    path: ./log
    name: ${logging.file.path}/cards.log